apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
  interval: 1h
  install:
    remediation:
      retries: 3
  uninstall:
    timeout: 5m
    disableHooks: false
    keepHistory: false
