apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: crossplane-system
spec:
  interval: 12h
  url: https://charts.crossplane.io/stable


#  kubectl create namespace crossplane-system
#  helm repo add crossplane-stable https://charts.crossplane.io/stable
#  helm repo update
#  helm install crossplane --namespace crossplane-system crossplane-stable/crossplane
